import { TravelTip } from "@/types";

import ReportSection from "./ReportSection";
import ReportText from "./ReportText";
import SectionHeading from "./SectionHeading";

interface Props {
  tips: TravelTip[];
}

export default function FinalRecommendations({
  tips,
}: Props) {
  return (
    <ReportSection>
      <SectionHeading
        number={6}
        title="Travel Recommendations"
      />

      <div className="space-y-8">
        {tips.map((tip, index) => (
          <article
            key={tip.title}
            className="
              border-b
              border-[var(--paper-border)]
              pb-8

              last:border-b-0
              last:pb-0
            "
          >
            <div className="flex items-start gap-5">
              <div
                className="
                  mt-1

                  flex
                  h-8
                  w-8
                  shrink-0
                  items-center
                  justify-center

                  rounded-full

                  bg-[var(--sun)]

                  text-sm
                  font-bold
                  text-white
                "
              >
                {index + 1}
              </div>

              <div className="flex-1 space-y-3">
                <h3
                  className="
                    text-2xl
                    font-semibold
                    text-[var(--paper-text)]
                  "
                >
                  {tip.title}
                </h3>

                <ReportText>
                  {tip.description}
                </ReportText>
              </div>
            </div>
          </article>
        ))}
      </div>

      {/* Closing Note */}

      <div
        className="
          border-t
          border-[var(--paper-border)]
          pt-10
          space-y-6
        "
      >
        <h3
          className="
            text-3xl
            font-semibold
            text-[var(--paper-text)]
          "
        >
          Have an amazing trip!
        </h3>

        <div className="space-y-5">
          <ReportText>
            Your itinerary has been carefully prepared according to your
            destination, travel style, budget, and trip duration. While every
            effort has been made to recommend the best options, availability
            and prices may change over time.
          </ReportText>

          <ReportText>
            Before travelling, verify your bookings, carry digital and printed
            copies of important documents, and leave room in your schedule for
            spontaneous discoveries that often become the most memorable parts
            of a journey.
          </ReportText>
        </div>

        <div className="flex justify-center pt-6">
          <div
            className="
              rounded-md
              border
              border-[var(--paper-border)]
              bg-[var(--paper-soft)]

              px-8
              py-3

              font-mono
              text-[12px]
              font-medium
              uppercase
              tracking-[0.22em]

              text-[var(--paper-muted)]
            "
          >
            Generated by TripMate AI • Safe Travels
          </div>
        </div>
      </div>
    </ReportSection>
  );
}


